name: B9 - Deployment on EC2

on: 
  push: 
    braches: 
      - main
job:
  deployemnt:
    run-on: ubuntu-latest

    steps: 
    - name: checkout code from github repo
      uses: actions/checkout@v4
      - name: Run some commands

      run: |
        whoami
        ls -al
        pwd
        cat index.html
